### ISSUE TITLE
Repo lacks License

### ISSUE THREAD

**Issue by ablwr** [huytd/kanban-app#2]
I would like to know. :)

**Comment by huytd** [comment]
Well, since there's very little thing I have in this repo (the main program in Elm is in the different repo of mine, which is BSD-2-Clause, and almost 99% of the client code is from zserge/webview and Boscop/web-view). I'd be happy to make this WTFPL.

**Comment by ablwr** [comment]
Ahh touché 😆

**Comment by huytd** [comment]
:joy:
