### ISSUE TITLE
[Question] Are there any options to call rust function from javascript using that farmework? Without adding node.js

### ISSUE THREAD

**Issue by lalabuy948** [huytd/kanban-app#6]
For example: 
logic.rs => lib
main.rs => main bin to run the app with webview crate
script.js => event listener, button clicked => call logic::some_function()

**Comment by huytd** [comment]
Hi @lalabuy948, sorry for (too) late response :D Yes it's possible because we're using web-view crate, it expose an `invoke()` method so you can have a two way communication between JS and Rust code.
