### ISSUE TITLE
The OS X App only displays a window with black background

### ISSUE THREAD

**Issue by mardukbp** [huytd/kanban-app#8]
I built the web app and tested it in Firefox. I added an entry to the board. I then copied `dist.js` to the kanban-app repo and built the OS X bundle. Upon launching Kanban.app I only get a black window.

Thanks for sharing this! I really can't stand that a super simple app built with Electron weighs 100 MB+.

**Comment by mardukbp** [comment]
@huytd I compiled with `debug=true` and the JS console displays the error `Unexpected token '>'`. Any ideas?

**Comment by mardukbp** [comment]
@huytd It turns out that despite your efforts to make everything reproducible, Apple spoiled the party. The web app generated by webpack runs perfectly well in Firefox, but not in Safari. I am using macOS 10.11.6. My guess is that you are using macOS 10.12 or higher.

I did some experiments and the problem seems to be that in `main.js` you used arrow functions and `fetch`, which are not supported by Safari versions older than 10:

* https://caniuse.com/#feat=fetch
* https://caniuse.com/#search=arrow

Of course, this is a problem because web-view uses Safari's rendering engine.

It would be great if you provided a `main.js` file that is compatible with older versions of macOS.

**Comment by huytd** [comment]
Ah, yes, that might be the root cause. If so, we can fix it in the Kanelm project.

**Comment by mardukbp** [comment]
I opened an issue there. Closing this now.
